name: OSX MPI Build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  osx-mpi-build:
    runs-on: macos-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
             brew install gcc@13
             echo "OMPI_MPIF90=gfortran-13" >> $GITHUB_ENV
             brew install open-mpi
      - name: Configure OSX MPI
        run: |
             mkdir build
             cd build
             cmake .. -DMPI=TRUE -DCOMPILER=AUTO -DCMAKE_INSTALL_PREFIX=$(pwd)/../install
      - name: Build serial
        run: |
             cd build
             make -j2 install
      - name: Set environment variables
        run: |
             echo "DO_PARALLEL=mpirun -np 2" >> $GITHUB_ENV
             echo "QUICK_HOME=$PWD/install" >> $GITHUB_ENV
      - name: Test serial
        run: |
             cd install
             ./runtest --mpi --full
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
            name: serial-tests
            path: /home/runner/work/QUICK/QUICK/install/test/runs/serial
            retention-days: 3
