name: Intel Serial Build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  cmake-build:
    runs-on: ubuntu-latest 
    container:
      image: intel/oneapi-hpckit:latest # Use the latest Intel HPC Toolkit image

    steps:
      - uses: actions/checkout@v2
      - name: Create bin directory
        run: mkdir -p /github/home/bin
  
      - name: Create symbolic links for Intel oneAPI compilers
        run: |
          ln -s $(which icx) /github/home/bin/icc
          ln -s $(which icpx) /github/home/bin/icpc
          ln -s $(which ifort) /github/home/bin/ifort
  
      - name: Add bin directory to PATH
        run: echo "/github/home/bin" >> $GITHUB_PATH
      - name: Install deps
        run: |
             mkdir build
             cd build
             cmake .. -DCOMPILER=INTEL -DENABLEF=TRUE -DCMAKE_INSTALL_PREFIX=$(pwd)/../install
      - name: Build serial
        run: |
             cd build
             make -j2 install
      - name: Set environment variables
        run: echo "QUICK_HOME=$PWD/install" >> $GITHUB_ENV
      - name: Test serial
        run: |
             cd install
             ./runtest --serial --full
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
            name: serial-tests
            path: /home/runner/work/QUICK/QUICK/install/test/runs/serial
            retention-days: 3
